### ISSUE TITLE
no file receiving

### ISSUE THREAD

**Issue by Musicpac** [thelinuxchoice/whatshack#2]
only getting two files: .nomedia and .compactdisk_extended_attributes

help

**Comment by thelinuxchoice** [comment]
it upload from default folder on internal storage, use a file manager to check if you have files on:
/storage/emulated/0/WhatsApp/Media/

**Comment by Musicpac** [comment]
Okay my fault it just takes 3 minutes till my mobile starts uploading.

have a great day
